spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mysql://mysql-server:3306/demo?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root