kafka:
  consumer:
    servers: http://kafka-service:9092
    enable:
      auto:
        commit: true
    session:
      timeout: 20000
    auto:
      commit:
        interval: 100
      offset:
        reset:
          latest
    topic: test
    group:
      id: test
    concurrency: 10
  producer:
    servers: http://kafka-service:9092
    topic: test
    retries: 0
    batch.size: 4096
    linger: 1
    buffer:
      memory: 40960