aliyun:
  oss:
    access-key: LTAIiM3MZASlCyDE
    accessKeySecret: 2RBB3xBpOsU8Dfgv75i03CW1Q6wGsz
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: platform-wx
    domain: https://platform-wx.oss-cn-beijing.aliyuncs.com

qiniu:
  oss:
    access-key: owGiAWGn6DpU5zlrfLP4K9iQusahmspTW6PxRABW
    accessKeySecret: 5CBWKFd1pP-OSiusd1Bvhokp-ih4i3bs2QA2r-U2
    endpoint: http://payo7kq4i.bkt.clouddn.com
    bucketName: owenwangwen
