aliyun:
  oss:
    access-key: LTAIiM3MZASlCyDE
    accessKeySecret: 2RBB3xBpOsU8Dfgv75i03CW1Q6wGsz
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: platform-wx
    domain: https://platform-wx.oss-cn-beijing.aliyuncs.com

qiniu:
  oss:
    access-key: j8lWlajTA7JC2h3lfKRmoP7TlgR9nHPyiYLsItP_
    accessKeySecret: lqSnqS6DXxMknd1F5zMDmufXHX7Mutp7BeSCCE3E
    endpoint: http://pugech0l5.bkt.clouddn.com
    bucketName: aaa
spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB