server:
  port: 9411

spring:
  application:
    name: zipkin-server
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    web:
      server:
        auto-time-requests: false    #去除控制台异常

zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      hosts: http://es-server:9300
      #      username: elastic
      #      password: changeme
      cluster: my-application
      index: zipkin
      index-shards: 1
      index-replicas: 1
  collector:
    kafka:
      bootstrap-servers: kafka-service:9092
      zookeeper: zookeeper-service:2181
      topic: zipkin